name: VoteReward
main: LDX\VoteReward\Main
version: 3.0Î²
api: [1.0.0,2.0.0]
author: LDX
load: POSTWORLD
website: http://votereward.mcpe.me
commands:
  vote:
    description: "Checks to see if you've voted yet."
    usage: "/vote"
    permission: votereward.vote
permissions:
  votereward:
    description: "Allows access to all VoteReward features."
    default: op
    children:
      votereward.vote:
        description: "Allows access to using the vote command."
        default: true
