# Config file for VoteReward by LDX.

# Variables:
#   {USERNAME} ... The username of the player who voted. ............ Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ........ Commands and message.
#   {X} .......... The X coordinate of the player. .................. Commands only.
#   {Y} .......... The Y coordinate of the player. .................. Commands only.
#   {Z} .......... The Z coordinate of the player. .................. Commands only.

# Message to broadcast to the server when a player votes.
Message: "The player {NICKNAME} voted with /vote and got cool rewards!"

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:
  - "264:0:5"
  - "265:0:3"
  - "364:0:5"

# List of commands to execute when a player votes.
Commands:
  - "particle magicCrit {X} {Y} {Z} 3 3 3 3 100 force"
